### PR TITLE
Implement a better parser for APT Json output

### PR DESCRIPTION
**Pull request by tale**
The current implementation of `APTWrapper.packageOperations` in the backend has many issues. It doesn't have strict codable types, it's slow, and it's only built to support APT output given by Procursus. As a result, I've implemented a new system, one that properly leverages Decodables to parse the JSON output returned by APT.

This brings performance improvements over the older system and it also results in a cleaner implementation of the `DownloadManager`. There is no longer a need to check for keys that may or may not exist on the output of the `packageOperations` function because of the new `APTWrapper.operationList`, which returns a struct.

Another hidden benefit is the built-in support for both separated JSON (Procursus) and a full JSON object (Elucubratus), helping Sileo reach one of its goals of officially working on both prominent jailbreaking bootstraps in the community at this time.

### CODE REVIEW

**Review by elihwyma — APPROVED** [review]
Looks good to me

**Comment by Diatrus** [comment]
I’ll have a look at this within a week

**Comment by Diatrus** [comment]
Note: Tested on a fresh Procursus Chimera install. Dep resolution was fine.

**Comment by tale** [comment]
Looks like I forgot to account for "Purg" as an operation type, will do that before flattening my commits :)

**Review by Diatrus — APPROVED** [review]

**Pull request merged**
