### PR TITLE
Fix and Update Turkish Translations

### PR DESCRIPTION
**Pull request by CanerKaraca23**
Fix and Update Turkish Translations.

### CODE REVIEW

**Comment by CanerKaraca23** [comment]
I don't know how editing Localizable.stringsdict or it's necessary to edit.

**Comment by worldlydev** [comment]
> I don't know how editing Localizable.stringsdict and don't know it's necessary to edit.

Take a look at: https://github.com/Sileo/Sileo/blob/94c712d37b0e70b7ea4b863e718e04f5fbeede79/Sileo/Sileo/ar.lproj/Localizable.stringsdict

The strings in Arabic should be quite easy to see in that file. Those are the only strings that need translating. 

I would copy localizable.stringsdict from base.lproj and than translate the strings you can easily see in the file above.

**Comment by CanerKaraca23** [comment]
> > I don't know how editing Localizable.stringsdict and don't know it's necessary to edit.
> 
> Take a look at: https://github.com/Sileo/Sileo/blob/94c712d37b0e70b7ea4b863e718e04f5fbeede79/Sileo/Sileo/ar.lproj/Localizable.stringsdict
> 
> The strings in Arabic should be quite easy to see in that file. Those are the only strings that need translating.
> 
> I would copy localizable.stringsdict from base.lproj and than translate the strings you can easily see in the file above.

Thanks, i copied from base and edited.

**Comment by worldlydev** [comment]
Looks good to me

**Comment by CharlieWhile13** [comment]
Will merge later today if no new suggestions are made

**Pull request merged**
