### PR TITLE
Remove .idea from being commited.

### PR DESCRIPTION
**Pull request by ChachyDev**

### CODE REVIEW

**Comment by kirb** [comment]
GitHub’s official [gitignore template](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore) for IDEA ignores only specific files. Does that make more sense? Not sure who committed .idea, I guess they were using AppCode?

Also, this doesn’t actually remove the .idea/ dir.

**Comment by kabiroberai** [comment]
@kirb it appears to be an artefact from https://github.com/coolstar/SileoApp/commit/fb5ecf1f25c0f41176218b3349a4bcd828cd1839

**Comment by kirb** [comment]
Hm, yes, let’s remove .idea then. That shouldn’t have been PR’d or merged with the .idea files included really. Oh well.

**Comment by salemkmsr** [comment]
> Seems a bit unnecessary, wait for @coolstar to take a look at it :)

**Comment by salemkmsr** [comment]
> Seems a bit unnecessary, wait for @coolstar to take a look at it :)

**Pull request merged**
