### PR TITLE
Add ability to create, import, export and use custom themes within Sileo

### PR DESCRIPTION
**Pull request by SerenaKit**
This Pull Request adds the ability to create, export, import, and use themes in Sileo

there is a new button in the Themes section of settings by the name of “Manage Themes” (as seen the image below) 
16551175-E865-4E9D-B042-80F896434702

Upon clicking “Manage Themes”, the user is taken to this section where it shows their themes. A new theme could be created by pressing on the “+” button on the top, which then brings them to the view shown below: 
5AA50F22-7156-435B-B60D-9E163B120B2A

The name can be customized by pressing on “Set Name”.

Users can select the colors for each theme component in that view, then press “Create Theme” to create the theme, themes can also be exported and imported, as shown here: 
C0DDBA27-C467-4F9C-8CAB-81E485FE4806

themes can also be individually exported and removed when swiped on.

### CODE REVIEW

**Comment by NguyenASang** [comment]
@CFSerena Why do you close this ? It looks really good

**Comment by CFSerena** [comment]
Because I’m annoying and petty as fuck

**Comment by NguyenASang** [comment]
> Because I’m annoying and petty as fuck

No, I don't think so, your changes are so so good.
Can you send me the deb of your changes, I really like it.

**Comment by CFSerena** [comment]
I cannot redistrube devs, and, except if the maintainers ask for this pr to be opened again to merge it, then this feature is going to be dead in the grave.

Sorry ❤️‍🩹

**Comment by CFSerena** [comment]
@NguyenASang reopening because of support from a few others, I won’t close it this time

**Comment by idklol16637** [comment]
I suggested this!

**Pull request merged**
