### PR TITLE
Add Chinese Traditional translations

### PR DESCRIPTION
**Pull request by terry3041**
[zh-Hant.lproj.zip](https://github.com/Sileo/Sileo/files/4631875/zh-Hant.lproj.zip) in case someone wants to try it out.

### CODE REVIEW

**Comment by deontw** [comment]
I have the files for Chinese traditional localization
[Chinese.Traditional.zip](https://github.com/Sileo/Sileo/files/4619700/Chinese.Traditional.zip)

**Comment by terry3041** [comment]
@deontw I have translated it into Traditional Chinese already. Why are you doing it again?

**Comment by deontw** [comment]
What?😂 I do not know. I takes me about a week to translate Sileo. Sorry, but you can have a look at my translations. May give you some suggests or ideas. Thanks for your work.

從我的iPhone傳送

terry3041 <notifications@github.com> 於 2020年5月13日 上午11:56 寫道：

﻿

@deontw<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdeontw&data=02%7C01%7C%7C32a75ab10f4d4d69ff0f08d7f6f199a5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637249389827116484&sdata=0JgvTztUVPzpsspHS4WUGnKXeVRNxiqCIdXnskpveaM%3D&reserved=0> I have translated it into Traditional Chinese already. Why are you doing it again?

**Comment by deontw** [comment]
What?😂 I do not know. I takes me about a week to translate Sileo. Sorry, but you can have a look at my translations. May give you some suggests or ideas. Thanks for your work.

**Comment by deontw** [comment]
Will this translations will be add in the new sileo？

**Comment by terry3041** [comment]
@deontw It should be. That's why I am making a pull request. You can try it out by downloading my translation on the top.

**Pull request closed without merging**
