### PR TITLE
new german translation - Update Localizable.strings

### PR DESCRIPTION
**Pull request by pimpmyidevice**

### CODE REVIEW

**Comment by CharlieWhile13** [comment]
Please add the following keys 
```xml
"Auto_Complete_Queue" = //"Auto Complete Queue";
"Enable_Analytics" = //"Enable Analytics";
"View_Depiction" = //"View Depiction";
```
and remove the keys
```xml
"Package_Filter_User" 
"Package_Filter_PowerUser" 
"Package_Filter_Dev"
```

**Comment by pimpmyidevice** [comment]
Okay.

**Comment by pimpmyidevice** [comment]
Done ✔️

**Comment by CharlieWhile13** [comment]
Looks good to me. I'll verify with other people now.

**Review by devhot1984 — APPROVED** [review]
# **[Developer](https://dandeveloper.carrd.co)**

*wow! i like it*

**Comment by pimpmyidevice** [comment]
Will this be merged to one of the next updates? :)

**Comment by CharlieWhile13** [comment]
Yes German Translations will be improved in the next update

**Pull request closed without merging**
