### PR TITLE
Use UIActivityViewController (iOS Share Sheet) instead of copying to …

### PR DESCRIPTION
**Pull request by CFSerena**
…clipboard when exporting Sources/Packages

### CODE REVIEW

**Review by 23Aaron — APPROVED** [review]

**Review by 23Aaron — CHANGES_REQUESTED** [review]
submit ipad fix before approval

**Review by 23Aaron — APPROVED** [review]
iPad fixes tested and verified

**Review by elihwyma — APPROVED** [review]
lgtm

**Comment by CFSerena** [comment]
@elihwyma Thanks, just wanted to ask, I think it would be better to remove the prompt asking the user if they want to copy the list, since it now prompts the share sheet instead of overwriting the user clipboard, should I push the change? I already have it locally and it works on my phone

**Comment by elihwyma** [comment]
Yes

**Comment by CFSerena** [comment]
Alright, thanks!

**Review by elihwyma — CHANGES_REQUESTED** [review]
This is a bad idea

**Comment by CFSerena** [comment]
Which part of it is?

**Comment by CFSerena** [comment]
Rebased the changes to be done to the dev branch, which seems to have been a mistake.. sigh

**Comment by CFSerena** [comment]
Closing and re-opening into another one because of git conflict issues

**Pull request closed without merging**
