### PR TITLE
Add Russian localizations to Sileo

### PR DESCRIPTION
**Pull request by worldlydev**
Original PR #23. Closed due to rebasing. Credit to @gkeep

### CODE REVIEW

**Comment by worldlydev** [comment]
_This isn't a duplicate of the original PR. I have added the newest strings and removed those no longer in use._

**Strings that need updating:**

"About" = "About";

"OK" = "ОК";

"Theme" = "Theme";
"Tint_Color" = "Tint Color";
"Reset_Tint_Color" = "Reset Tint Color";
"Auto_Complete_Queue" = "Auto Complete Queue";
"Enable_Analytics" = "Enable Analytics";

"Sileo_Light" = "Sileo Light";
"Sileo_Dark" = "Sileo Dark";
"Sileo_Adaptive" = "Sileo Adaptive";
"System" = "System";

"View_Depiction" = "View Depiction";

**Comment by gkeep** [comment]
```
"About" = "О программе";

"OK" = "ОК";

"Theme" = "Тема";
"Tint_Color" = "Цвет оттенка";
"Reset_Tint_Color" = "Сбросить цвет оттенка";
"Auto_Complete_Queue" = "Автоматически завершать очередь";
"Enable_Analytics" = "Включить аналитику";

"Sileo_Light" = "Светлый Sileo";
"Sileo_Dark" = "Темный Sileo";
"Sileo_Adaptive" = "Адаптивный Sileo";
"System" = "Система";

"View_Depiction" = "Посмотреть описание";
```

Thanks for doing all the hard work, by the way.

**Comment by worldlydev** [comment]
> ```
> "About" = "О программе";
> 
> "OK" = "ОК";
> 
> "Theme" = "Тема";
> "Tint_Color" = "Цвет оттенка";
> "Reset_Tint_Color" = "Сбросить цвет оттенка";
> "Auto_Complete_Queue" = "Автоматически завершать очередь";
> "Enable_Analytics" = "Включить аналитику";
> 
> "Sileo_Light" = "Светлый Sileo";
> "Sileo_Dark" = "Темный Sileo";
> "Sileo_Adaptive" = "Адаптивный Sileo";
> "System" = "Система";
> 
> "View_Depiction" = "Посмотреть описание";
> ```
> 
> Thanks for doing all the hard work, by the way.

No issue, I'm bored out of my mind atm anyways so might as well do something. 

It should be ready to merge now.

**Comment by CharlieWhile13** [comment]
If no new suggestions are made I will merge later today

**Comment by gkeep** [comment]
Sounds good.

By the way, are you still considering using services like Crowdin or Transifex?

**Pull request merged**
