### PR TITLE
WIP: Support for Elucubratus APT::Format::JSON output format

### PR DESCRIPTION
**Pull request by kirb**
After discussion with @sbingner, we decided we should standardise on a slightly modified version of the `-oAPT::Format::for-sileo=true` output we currently use on Electra/Chimera.

Rather than output like this with a JSON object per line:

```json
{"Version":"1.0.7~beta5-coolstar-1","Package":"com.rpetrich.rocketbootstrap","Release":"Chimera Repo:1.0\/stable [iphoneos-arm]","Type":"Inst"}
{"Version":"1:0.0.1.5-1","Package":"org.thebigboss.libstatus9","Release":"BigBoss+:0.9\/stable [iphoneos-arm]","Type":"Inst"}
{"Version":"2.2.4~coolstar2","Package":"preferenceloader","Release":"Chimera Repo:1.0\/stable [iphoneos-arm]","Type":"Inst"}
{"Version":"1.14","Package":"ws.hbang.common","Release":"Chariz:0.9\/stable [iphoneos-arm]","Type":"Inst"}
{"Version":"2.4","Package":"ws.hbang.typestatus2","Release":"Packix:1.1\/stable [iphoneos-arm]","Type":"Inst"}
```

or for error:

```json
{"ws.hbang.typestatusplus":[[{"Reason":"12.4 is to be installed","Package":"firmware","Type":"Depends","VersionSummary":"< 10.3"}],[{"Reason":"it is not going to be installed","Package":"ws.hbang.typestatus2","Type":"Depends","VersionSummary":">= 2.2.1"}],[{"Reason":"12.4 is to be installed","Package":"firmware","Type":"Recommends","VersionSummary":"< 9.2"},{"Package":"libmoorecon","Type":"Recommends"}]]}
```

… we’ll instead get one big JSON object:

```json
{
  "operations" : [
    {
      "Package" : "org.thebigboss.libstatus9",
      "Release" : "BigBoss:1.0\/stable [iphoneos-arm]",
      "Type" : "Inst",
      "CandidateVersion" : "1:0.0.1.5-1"
    },
    {
      "Package" : "ws.hbang.typestatus2",
      "Release" : "Packix:1.1\/stable [iphoneos-arm]",
      "Type" : "Inst",
      "CandidateVersion" : "2.4"
    },
    {
      "Package" : "org.thebigboss.libstatus9",
      "Release" : "BigBoss:1.0\/stable [iphoneos-arm]",
      "Type" : "Conf",
      "CandidateVersion" : "1:0.0.1.5-1"
    },
    {
      "Package" : "ws.hbang.typestatus2",
      "Release" : "Packix:1.1\/stable [iphoneos-arm]",
      "Type" : "Conf",
      "CandidateVersion" : "2.4"
    }
  ]
}
```

or for error:

```json
{
  "brokenPackages" : {
    "ws.hbang.typestatusplus" : [
      [
        {
          "VerStr" : "13.3",
          "Reason" : "13.3 is to be installed",
          "Package" : "firmware",
          "CompType" : "<",
          "Type" : "Depends",
          "VersionSummary" : "< 10.3",
          "TargetVer" : "10.3"
        }
      ],
      [
        {
          "Reason" : "it is not going to be installed",
          "Package" : "ws.hbang.typestatus2",
          "Type" : "Depends",
          "VersionSummary" : ">= 2.2.1",
          "CompType" : ">=",
          "TargetVer" : "2.2.1"
        }
      ],
      [
        {
          "VerStr" : "13.3",
          "Reason" : "13.3 is to be installed",
          "Package" : "firmware",
          "CompType" : "<",
          "Type" : "Recommends",
          "VersionSummary" : "< 9.2",
          "TargetVer" : "9.2"
        },
        {
          "Package" : "libmoorecon",
          "Type" : "Recommends"
        }
      ]
    ]
  }
}
```

Essentially still the same output, just in one big JSON object and pretty-printed.

We should also try to add unit tests for this (see #8). This is extremely important to get right, there is absolutely zero room for bugs and regressions here. It needs to work, or users are SOL and it’s hard for us to deploy a patch.

### CODE REVIEW

**Comment by coolstar** [comment]
A good test for this would be to bootstrap a device with Electra 1.0's bootstrap, install an APT build with this patch + Sileo, and see if it can install all the package upgrades

This test would need to be done with the original for-sileo patch in APT as well as this one as compatibility with both is needed

**Comment by kabiroberai** [comment]
@kirb what’s the rationale behind pretty-printing the output? A minified version would probably be more efficient to parse. Perhaps a flag could be added to toggle pretty-printing?

**Comment by kirb** [comment]
Don’t recall why, but I don’t think there’s any issue with it either. Performance of skipping past some spaces will be negligible, likely won’t even show any difference in Instruments. The bottleneck won’t be the JSON encode/decode.

@sbingner do you remember why exactly we made this pretty printed?

**Comment by sbingner** [comment]
Pretty sure it was mostly so it was readable for debugging etc... we talked about maybe adding a flag to make it ugly-printed but didn't because like you said it isn't really any more difficult to parse

**Pull request closed without merging**
