### PR TITLE
Add Norwegian Bokmål localizations to Sileo

### PR DESCRIPTION
**Pull request by worldlydev**
Second attempt at this. Hopefully all good. #18

### CODE REVIEW

**Comment by worldlydev** [comment]
Is it good to merge or do I need to make any changes?

**Comment by CharlieWhile13** [comment]
I will add the Xcode files now, and then it should be good to merge

**Comment by CharlieWhile13** [comment]
Can you reopen merging into branch `amy`

**Comment by worldlydev** [comment]
> amy

Will do. Give me a min

**Pull request closed without merging**
